Behaviors:
    Robot:
        Sensors:
            Cameras:
                Camera_0:
                    Name: 'camera_0'
                    Topic: '/carla/ego_vehicle/rgb_front/image'
                Camera_1:
                    Name: 'camera_1'
                    Topic: '/carla/ego_vehicle/rgb_view/image'
                Camera_2:
                    Name: 'camera_2'
                    Topic: '/carla/ego_vehicle/semantic_segmentation_front/image'
                Camera_3:
                    Name: 'camera_3'
                    Topic: '/carla/ego_vehicle/dvs_front/image'
            Pose3D:
                Pose3D_0:
                    Name: 'pose3d_0'
                    Topic: '/carla/ego_vehicle/odometry'
            BirdEyeView:
                BirdEyeView_0:
                    Name: 'bird_eye_view_0'
                    Topic: ''
            Speedometer:
                Speedometer_0:
                    Name: 'speedometer_0'
                    Topic: '/carla/ego_vehicle/speedometer'
            IMU:
                IMU_0:
                    Name: 'imu_0'
                    Topic: '/carla/ego_vehicle/imu'
        Actuators:
            CARLA_Motors:
                Motors_0:
                    Name: 'motors_0'
                    Topic: '/carla/ego_vehicle/vehicle_control_cmd'
                    MaxV: 3
                    MaxW: 0.3
        BrainPath: 'brains/CARLA/brain_carla_TCP.py'
        PilotTimeCycle: 50
        AsyncMode: True
        Parameters:
            Model: 'best_model.ckpt'
            ImageCropped: True
            ImageSize: [ 100,50 ]
            ImageNormalized: True
            PredictionsNormalized: True
            GPU: True
            UseOptimized: False
            ImageTranform: ''
        Type: 'CARLA'
    Simulation:
        World: configs/CARLA/CARLA_launch_files/town_02_anticlockwise_imitation_learning.launch
        RandomSpawnPoint: False
        TestSuite: 'Town02_two_turns'
    Dataset:
        In: '/tmp/my_bag.bag'
        Out: ''
    Stats:
        Out: './'
        PerfectLap: './perfect_bags/lap-simple-circuit.bag'
    Layout:
        Frame_0:
            Name: frame_0
            Geometry: [1, 1, 1, 1]
            Data: rgbimage
        Frame_1:
            Name: frame_1
            Geometry: [0, 1, 1, 1]
            Data: rgbimage
        Frame_2:
            Name: frame_2
            Geometry: [0, 2, 1, 1]
            Data: rgbimage
        Frame_3:
            Name: frame_3
            Geometry: [1, 2, 1, 1]
            Data: rgbimage
