Behaviors:
    Robot:
        Sensors:
            Cameras:
                Camera_0:
                    Name: 'camera_0'
                    Topic: '/carla/ego_vehicle/rgb_front/image'
                Camera_1:
                    Name: 'camera_1'
                    Topic: '/carla/ego_vehicle/rgb_view/image'
                Camera_2:
                    Name: 'camera_2'
                    Topic: '/carla/ego_vehicle/semantic_segmentation_front/image'
                Camera_3:
                    Name: 'camera_3'
                    Topic: '/carla/ego_vehicle/dvs_front/image'
            Pose3D:
                Pose3D_0:
                    Name: 'pose3d_0'
                    Topic: '/carla/ego_vehicle/odometry'
            BirdEyeView:
                BirdEyeView_0:
                    Name: 'bird_eye_view_0'
                    Topic: ''
        Actuators:
            CARLA_Motors:
                Motors_0:
                    Name: 'motors_0'
                    Topic: '/carla/ego_vehicle/vehicle_control_cmd'
                    MaxV: 3
                    MaxW: 0.3
                    
        BrainPath: [
            'brains/CARLA/tensorflow/brain_carla_bird_eye_deep_learning.py'
            ]
        PilotTimeCycle: 100
        Parameters:
            Model: [
                '20221214-102705_deepestLSTMTinyPilotNet_CARLA_14_12_dataset_bird_eye_300_epochs_no_flip_3_output_both_directions_all_towns_PAPER_cp.h5',
                ]
            ImageCropped: True
            ImageSize: [ 100,50 ]
            ImageNormalized: True
            PredictionsNormalized: True
            GPU: True
            UseOptimized: True
            ImageTranform: ''
        Type: 'CARLA'

        RandomSpawnPoint: True
    Experiment:
        Name: "Experiment name"
        Description: "Experiment description"
        Timeout: [10, 10, 10, 10, 10, 10, 10, 10] # for each world!
        Repetitions: 1
    Simulation:
        World: [


            configs/CARLA/CARLA_launch_files/town_04_anticlockwise_no_gui.launch,
            configs/CARLA/CARLA_launch_files/town_04_clockwise_no_gui.launch,

            configs/CARLA/CARLA_launch_files/town_05_anticlockwise_no_gui.launch,
            configs/CARLA/CARLA_launch_files/town_05_clockwise_no_gui.launch,

            configs/CARLA/CARLA_launch_files/town_06_anticlockwise_no_gui.launch,
            configs/CARLA/CARLA_launch_files/town_06_clockwise_no_gui.launch,

            configs/CARLA/CARLA_launch_files/town_07_anticlockwise_no_gui.launch,
            configs/CARLA/CARLA_launch_files/town_07_clockwise_no_gui.launch
            ]
    Dataset:
        In: '/tmp/my_bag.bag'
        Out: ''
    Stats:
        Out: './'
        PerfectLap: './perfect_bags/lap-simple-circuit.bag'
    Layout:
        Frame_0:
            Name: frame_0
            Geometry: [1, 1, 1, 1]
            Data: rgbimage
        Frame_1:
            Name: frame_1
            Geometry: [0, 1, 1, 1]
            Data: rgbimage
        Frame_2:
            Name: frame_2
            Geometry: [0, 2, 1, 1]
            Data: rgbimage
        Frame_3:
            Name: frame_3
            Geometry: [1, 2, 1, 1]
            Data: rgbimage
