settings:
  mode: inference
  task: dqn_follow_line # follow_line_gazebo, follow_lane_gazebo, autoparking_gazebo
  algorithm: dqn # qlearn, dqn, ddpg, ppo
  simulator: gazebo # openai, carla, gazebo, sumo
  environment_set: environments # gazebo_environments, carla_environments
  env: simple # simple, nurburgring, montreal, curves, simple_laser, manual, autoparking
  agent: f1 # f1, autoparkingRL, auto_carla, mountain_car, robot_mesh, cartpole, turtlebot
  actions: hard # simple, medium, hard, test
  states: sp10 #image, sp1 (simplified perception with 1 point), sp3 (simplified perception with 3 points), spn (simplified perception with n points)
  rewards: followline_center # rewards_followline_center
  framework: TensorFlow # TensorFlow, Pytorch
  total_episodes: 5
  training_time: 6
  models_dir: "./checkpoints"
  logs_dir: "./logs"
  metrics_dir: "./metrics"

ros:
  ros_master_uri: "11311"
  gazebo_master_uri: "11345"

retraining:
  dqn:
    retrain_dqn_tf_model_name:

inference:
  dqn:
    inference_file: /home/ruben/Desktop/my-BehaviorMetrics/behavior_metrics/models/gazebo/rl_models/dqn/DQN_sp_16x16_LAPCOMPLETED_Max2951_Epoch267_inTime20231220-121204.model

algorithm:
  dqn:
    alpha: 0.8
    gamma: 0.9
    epsilon: 0.000001
    epsilon_discount: 0.9986
    epsilon_min: 0.05
    model_name: DQN_sp_16x16
    replay_memory_size: 50_000
    min_replay_memory_size: 1000
    minibatch_size: 64
    update_target_every: 5
    memory_fraction: 0.20
    buffer_capacity: 100_000
    batch_size: 64

agent:
  f1:
    camera_params:
      width: 640
      height: 480
      center_image: 320
      raw_image: False
      image_resizing: 100
      new_image_size: 32
      num_regions: 16
      lower_limit: 220

states:
  image:
    0: [3]
  sp1:
    0: [10]
  sp3:
    0: [5, 15, 22]
  sp5:
    0: [13, 25, 60, 110, 160]
  sp10:
    0: [3, 15, 30, 45, 50, 70, 100, 120, 150, 190]
  spn:
    0: [10]

actions:
  simple:
    0: [5, 0]
    1: [0.5, 0.2]
    2: [0.5, -0.2]
  medium:
    0: [ 1, 0 ]
    1: [ 1, 1 ]
    2: [ 1, -1 ]
    3: [ 1, 0.5 ]
    4: [ 1, -0.5 ]
  hard:
    0: [7, 0]
    1: [4, 1,5]
    2: [4, -1,5]
    3: [3, 1]
    4: [3, -1]
    5: [2, 1]
    6: [2, -1]
    7: [1, 0.5]
    8: [1, -0.5]
  test:
    0: [0, 0]

rewards:
  followline_center:
    from_10: 10
    from_02: 2
    from_01: 1
    penal: -100
    min_reward: 5_000
    highest_reward: 100

environments:
  simple:
    env_name: F1Env-v0
    circuit_name: simple
    launchfile: simple_circuit.launch
    environment_folder: f1
    robot_name: f1_renault
    model_state_name: f1_renault # f1_renault_multicamera_multilaser
    start_pose: 0 # 0, 1, 2, 3, 4
    alternate_pose: False
    estimated_steps: 50
    sensor: camera
    save_episodes: 5
    save_every_step: 10
    lap_completed: False
    save_model: True
    save_positions: True
    debug_level: DEBUG
    telemetry: False
    telemetry_mask: False
    plotter_graphic: False
    circuit_positions_set:
      0: [53.462, -41.988, 0.004, 0, 0, 1.57, -1.57]
      1: [53.462, -8.734, 0.004, 0, 0, 1.57, -1.57]
      2: [39.712, -30.741, 0.004, 0, 0, 1.56, 1.56]
      3: [-6.861, -36.481, 0.004, 0, 0.01, -0.858, 0.613]
      4: [20.043, 37.130, 0.003, 0, 0.103, -1.4383, -1.4383]
